// services/user-service.js
const bcrypt = require("bcryptjs");
const jwt = require("jsonwebtoken");
const User = require("../models/user.model"); // your original model
// Allowed roles (if needed elsewhere)
const allowedRoles = ["admin", "partner", "franchise", "customer"];

// Keep validators here as requested
exports.isValidEmail = (email) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);

exports.isValidPassword = (password) =>
  typeof password === "string" &&
  password.length >= 8 &&
  /[a-z]/.test(password) &&
  /[A-Z]/.test(password) &&
  /\d/.test(password) &&
  /[!@#$%^&*(),.?":{}|<>]/.test(password);

// Create user
exports.createUser = async ({ email, password, selectedPlan }) => {
  try {
    const cleanEmail = email.trim().toLowerCase();

    const existingUser = await User.findOne({ email: cleanEmail });
    if (existingUser) throw new Error("EMAIL_EXISTS");

    const hashedPassword = await bcrypt.hash(password, 10);

    const user = await User.create({
      email: cleanEmail,
      password: hashedPassword,
      role: selectedPlan ? "customer" : "",
      isActive: true,
      registrationComplete: false,
    });

    return user;
  } catch (error) {
    console.error("Error in createUser:", error);
    throw error;
  }
};

// Find by email
exports.findUserByEmail = async (email) => {
  try {
    const user = await User.findOne({ email: email.trim().toLowerCase() });
    return user;
  } catch (error) {
    console.error("Error in findUserByEmail:", error);
    throw error;
  }
};

// Find by id
exports.findUserById = async (id) => {
  try {
    const user = await User.findById(id);
    return user;
  } catch (error) {
    console.error("Error in findUserById:", error);
    throw error;
  }
};

// Hash password (exposed)
exports.hashPassword = async (password) => {
  try {
    return await bcrypt.hash(password, 10);
  } catch (error) {
    console.error("Error in hashPassword:", error);
    throw error;
  }
};

// Generate reset token (JWT style)
exports.generateResetToken = (userId, secret, expiresIn = "1h") => {
  if (!secret) {
    throw new Error("JWT secret is required");
  }
  return jwt.sign({ userId }, secret, { expiresIn });
};

// Verify token (JWT style)
exports.verifyToken = (token, secret) => {
  if (!secret) {
    throw new Error("JWT secret is required");
  }
  return jwt.verify(token, secret);
};

// AUTO-CREATE USER FOR CARD
exports.autoCreateUserForCard = async (email, selectedPlan = null) => {
  try {
    const cleanEmail = email.trim().toLowerCase();

    // Check if user already exists
    const existingUser = await User.findOne({ email: cleanEmail });
    
    if (existingUser) {
      // Update role to customer if not already set
      if (selectedPlan && existingUser.role === '') {
        existingUser.role = 'customer';
        await existingUser.save();
      }
      
      return {
        success: true,
        exists: true,
        user: {
          _id: existingUser._id,
          email: existingUser.email,
          role: existingUser.role,
          registrationComplete: existingUser.registrationComplete
        },
        message: 'User already exists'
      };
    }
    
    // Auto-generate a password
    const autoPassword = Math.random().toString(36).slice(-8) + 
                        Math.random().toString(36).slice(-8);
    
    // Create new user
    const user = await User.create({
      email: cleanEmail,
      password: await bcrypt.hash(autoPassword, 10),
      role: selectedPlan ? 'customer' : '',
      isActive: true,
      registrationComplete: false,
      isAutoGenerated: true
    });
    
    return {
      success: true,
      exists: false,
      user: {
        _id: user._id,
        email: user.email,
        role: user.role,
        registrationComplete: user.registrationComplete,
        isAutoGenerated: true
      },
      message: 'User created automatically'
    };
    
  } catch (error) {
    console.error('Auto-create user error:', error);
    return {
      success: false,
      error: error.message
    };
  }
};